In [1]:
import pandas as pd

# 1. Situering

Wat is het doel van dit model?
* Kijken welke factoren een invloed hebben op de kijkcijfers.
* Kijkcijfers kunnen voorspellen.

Hoe zal het model gebruikt worden?
* Programma's plannen: wanneer zenden we best een nieuw programma uit?
* Verkopen van reclame blokken op basis van het aantal kijkers dat we op bepaalde momenten hebben.

Input:
* Kijkcijfer data (top 20 vlaamse programma's vanaf 2016-10-01)
* Weer data (open-meteo data)
* Zonsopgang en -ondergang data (open-meteo data)

Welke technieken gebruiken we?
* Supervised learning: we hebben labels (ratings)
* Regressie: we voorspellen een getal
* Batch learning: er is geen continue flow van nieuwe data

Performance measures:
* MAPE
* RMSE
* MAE

*We meten de afstand tussen onze voorspellingsvector en de target values vector. In percentages voor MAPE en in het aantal kijkers voor RMSE en MAE*

# 2. Data verzamelen

## 2.1 Ratings data

In [src/ratings_data.py](./src/ratings_data.py) kan je zie hoe de data opgehaald en verwerkt wordt.

In [4]:
ratings_df = pd.read_parquet('ratings_data.parquet')

## 2.1 Opschonen van ratings data

In [5]:
ratings_df.head()

            programma zender      datum     start      duur  kijkers
0  HET 7 UUR-JOURNAAL    EEN 2016-10-01  19:00:05  00:31:38   721850
1    FC DE KAMPIOENEN    EEN 2016-10-01  20:41:00  00:38:39   709606
2        WEG ZIJN WIJ    EEN 2016-10-01  20:13:36  00:24:44   548239
3    IEDEREEN BEROEMD    EEN 2016-10-01  19:38:10  00:29:01   523610
4      COMEDY TOPPERS    VTM 2016-10-01  19:52:06  00:24:40   496216

In [8]:
sorted_by_date = ratings_df.sort_values(by="start", ascending=False)
sorted_by_date.head(10)

,programma,zender,datum,start,duur,kijkers
9088,STAN VAN SAMANG IN 'T GROOT,VTM,2017-12-31,25:29:51,00:30:09,201048
23681,LOSLOPEND WILD & GEVOGELTE,EEN,2019-12-31,25:19:13,00:27:36,391405
48626,HET JOURNAAL LAAT,VRT 1,2023-05-13,25:15:21,00:23:11,265014
19175,HET JOURNAAL LAAT,EEN,2019-05-18,25:13:44,00:17:34,231163
41195,HET JOURNAAL LAAT,EEN,2022-05-14,25:12:41,00:17:48,301029
63327,HET JOURNAAL LAAT,VRT 1,2025-05-17,25:10:17,00:20:28,250428
55906,HET JOURNAAL LAAT,VRT 1,2024-05-11,24:59:41,00:22:28,273047
34846,FIRST DATES,EEN,2021-07-11,24:56:43,00:45:58,65969
11736,HET JOURNAAL LAAT,EEN,2018-05-12,24:51:28,00:16:29,254994
58838,BILLIE VS BENJAMIN,VTM,2024-10-04,24:49:33,00:36:28,115096

Some records have a starting time of 24:xx:xx or 25:xx:xx with the wrong date. They should get moved to the next day.

In [ ]:
from src.correct_dates import correct_start_times

ratings_df_corrected_dates = correct_start_times(ratings_df)

Found 40 faulty records to correct
Record 1810: 2016-12-31 00:00:00 24:22:37 → 2017-01-01 00:22:37
Record 1814: 2016-12-31 00:00:00 24:34:48 → 2017-01-01 00:34:48
Record 4451: 2017-05-13 00:00:00 24:46:08 → 2017-05-14 00:46:08
Record 5744: 2017-07-16 00:00:00 24:07:25 → 2017-07-17 00:07:25
Record 9078: 2017-12-31 00:00:00 24:25:28 → 2018-01-01 00:25:28
Record 9081: 2017-12-31 00:00:00 24:32:00 → 2018-01-01 00:32:00
Record 9088: 2017-12-31 00:00:00 25:29:51 → 2018-01-01 01:29:51
Record 11736: 2018-05-12 00:00:00 24:51:28 → 2018-05-13 00:51:28
Record 12742: 2018-07-01 00:00:00 24:10:40 → 2018-07-02 00:10:40
Record 12863: 2018-07-07 00:00:00 24:26:31 → 2018-07-08 00:26:31
Record 12946: 2018-07-11 00:00:00 24:19:14 → 2018-07-12 00:19:14
Record 16414: 2018-12-31 00:00:00 24:21:11 → 2019-01-01 00:21:11
Record 16418: 2018-12-31 00:00:00 24:01:02 → 2019-01-01 00:01:02
Record 19175: 2019-05-18 00:00:00 25:13:44 → 2019-05-19 01:13:44
Record 23671: 2019-12-31 00:00:00 24:18:42 → 2020-01-01 00:18:42
Record 23681: 2019-12-31 00:00:00 25:19:13 → 2020-01-01 01:19:13
Record 23686: 2019-12-31 00:00:00 24:14:58 → 2020-01-01 00:14:58
Record 34846: 2021-07-11 00:00:00 24:56:43 → 2021-07-12 00:56:43
Record 38301: 2021-12-31 00:00:00 24:03:38 → 2022-01-01 00:03:38
Record 38305: 2021-12-31 00:00:00 24:34:56 → 2022-01-01 00:34:56
Record 41195: 2022-05-14 00:00:00 25:12:41 → 2022-05-15 01:12:41
Record 45537: 2022-12-09 00:00:00 24:06:51 → 2022-12-10 00:06:51
Record 45975: 2022-12-31 00:00:00 24:19:10 → 2023-01-01 00:19:10
Record 48626: 2023-05-13 00:00:00 25:15:21 → 2023-05-14 01:15:21
Record 53271: 2023-12-31 00:00:00 24:44:13 → 2024-01-01 00:44:13
Record 53397: 2024-01-06 00:00:00 24:08:31 → 2024-01-07 00:08:31
Record 55875: 2024-05-09 00:00:00 24:05:55 → 2024-05-10 00:05:55
Record 55906: 2024-05-11 00:00:00 24:59:41 → 2024-05-12 00:59:41
Record 56490: 2024-06-09 00:00:00 24:32:54 → 2024-06-10 00:32:54
Record 57196: 2024-07-14 00:00:00 24:06:56 → 2024-07-15 00:06:56
Record 57475: 2024-07-28 00:00:00 24:07:57 → 2024-07-29 00:07:57
Record 57598: 2024-08-03 00:00:00 24:07:00 → 2024-08-04 00:07:00
Record 57758: 2024-08-11 00:00:00 24:10:33 → 2024-08-12 00:10:33
Record 58555: 2024-09-20 00:00:00 24:07:16 → 2024-09-21 00:07:16
Record 58838: 2024-10-04 00:00:00 24:49:33 → 2024-10-05 00:49:33
Record 59012: 2024-10-13 00:00:00 24:02:26 → 2024-10-14 00:02:26
Record 60536: 2024-12-28 00:00:00 24:09:14 → 2024-12-29 00:09:14
Record 60582: 2024-12-31 00:00:00 24:00:46 → 2025-01-01 00:00:46
Record 60594: 2024-12-31 00:00:00 24:37:48 → 2025-01-01 00:37:48
Record 63327: 2025-05-17 00:00:00 25:10:17 → 2025-05-18 01:10:17

Correction complete! Updated 40 records.