# Import packages

In [109]:
import sys
import sklearn
import numpy as np
import pandas as pd
import os
import matplotlib as mpl
import matplotlib.pyplot as plt
from datetime import datetime

# 1. Situering

Wat is het doel van dit model?
* Kijken welke factoren een invloed hebben op de kijkcijfers.
* Kijkcijfers kunnen voorspellen.

Hoe zal het model gebruikt worden?
* Programma's plannen: wanneer zenden we best een nieuw programma uit?
* Verkopen van reclame blokken op basis van het aantal kijkers dat we op bepaalde momenten hebben.

Input:
* Ratings data (top 20 vlaamse programma's vanaf 2016-10-01)
* Weer data (open data van KMI)
* Zonsopgang en -ondergang data

Welke technieken gebruiken we?
* Supervised learning: we hebben labels (ratings)
* Regressie: we voorspellen een getal
* Batch learning: er is geen continue flow van nieuwe data

Performance measures:
* MAPE
* RMSE
* MAE

*We meten de afstand tussen onze voorspellingsvector en de target values vector. In percentages voor MAPE en in het aantal kijkers voor RMSE en MAE*

# 2. Data verzamelen

## Opschonen en voorbereiden van ratings data

In [110]:
ratings_df = pd.read_csv('data/ratings.csv')

# Drop rijen met NaN values
ratings_df = ratings_df.dropna()
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63249 entries, 0 to 63249
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Programma  63249 non-null  object
 1   Zender     63249 non-null  object
 2   Datum      63249 non-null  object
 3   Start      63249 non-null  object
 4   Duur       63249 non-null  object
 5   Kijkers    63249 non-null  object
dtypes: object(6)
memory usage: 3.4+ MB

"Kijkers" kolom omzetten naar een integer type vergt nog extra bewerkingen:

In [111]:
# Verander de notatie van getallen (punten gebruiken als decimaalteken in plaats van komma's)
ratings_df['Kijkers'] = ratings_df['Kijkers'].str.replace('.', '').str.replace(',', '.')

# Eerst omzetten naar float (om decimalen te kunnen verwerken). Niet-numerieke waarden worden een NaN
ratings_df['Kijkers'] = pd.to_numeric(ratings_df['Kijkers'], errors='coerce')

# Verwijder NaN waarden
print(f"Number of rows with non-numeric values: {ratings_df['Kijkers'].isna().sum()}")
ratings_df = ratings_df.dropna(subset=['Kijkers'])

# Omzetten naar integer (dit rondt de decimalen af)
ratings_df['Kijkers'] = ratings_df['Kijkers'].astype(int)

Number of rows with non-numeric values: 1

De "Datum" kolom gaan we opsplitsen in bruikbaardere kolommen: jaar, maand, dag, week

In [112]:
ratings_df["Datum"] = pd.to_datetime(ratings_df["Datum"])

ratings_df["Jaar"] = ratings_df["Datum"].dt.year
ratings_df["Maand"] = ratings_df["Datum"].dt.month
ratings_df["Dag"] = ratings_df["Datum"].dt.day_of_week
ratings_df["Week"] = ratings_df["Datum"].dt.isocalendar().week

ratings_df.head()

,Programma,Zender,Datum,Start,Duur,Kijkers,Jaar,Maand,Dag,Week
0,HET 7 UUR-JOURNAAL,EEN,2016-10-01,19:00:05,00:31:38,721850,2016,10,5,39
1,FC DE KAMPIOENEN,EEN,2016-10-01,20:41:00,00:38:39,709606,2016,10,5,39
2,WEG ZIJN WIJ,EEN,2016-10-01,20:13:36,00:24:44,548239,2016,10,5,39
3,IEDEREEN BEROEMD,EEN,2016-10-01,19:38:10,00:29:01,523610,2016,10,5,39
4,COMEDY TOPPERS,VTM,2016-10-01,19:52:06,00:24:40,496216,2016,10,5,39

Wanneer we wat dichter naar de "Start" kolom kijken, zien we dat er toch enkele vreemde waarden tussen zitten.
Programma's na middernacht worden nog bij de verkeerde dag gezet en hun startuur is niet om te zetten naar een datetime.

In [113]:
sorted_by_date = ratings_df.sort_values(by="Start", ascending=True)
sorted_by_date.head(10)

,Programma,Zender,Datum,Start,Duur,Kijkers,Jaar,Maand,Dag,Week
30917,"NIELS DESTADSBADER, BOVEN DE WOLKEN",VTM,2020-12-31,00:07:05,01:31:14,293071,2020,12,3,53
30912,DE PLAYLIST,EEN,2020-12-31,00:11:26,00:28:32,458764,2020,12,3,53
34750,HET JOURNAAL LAAT,EEN,2021-07-11,00:35:26,00:15:32,218903,2021,7,6,27
33748,HET JOURNAAL LAAT,EEN,2021-05-22,00:58:11,00:16:11,461262,2021,5,5,20
35318,O.S. 2021 ATLETIEK - ABDI - KERSTEN - NAERT,EEN,2021-08-08,02:00:00,00:24:10,162616,2021,8,6,31
12794,PAPILLON,EEN,2018-07-07,02:00:00,00:18:59,73572,2018,7,5,27
43940,WIELRENNEN. WK. WEGRIT WOLLONGONG H.,EEN,2022-09-25,02:07:01,07:03:27,271278,2022,9,6,38
43923,WIELRENNEN. WK. WEGRIT WOLLONGONG D.,EEN,2022-09-24,06:01:26,03:42:13,165222,2022,9,5,38
43802,WIELRENNEN. WK. PLOEGENTIJDRIT WOLLONGONG H.,EEN,2022-09-18,07:02:03,02:03:25,277471,2022,9,6,37
57639,O.S. 2024 ATLETIEK. MARATHON H. - ABDI,VRT 1,2024-08-10,07:55:03,02:31:50,169815,2024,8,5,32

Er zijn 3 gevallen waar deze fout gebeurt: 24:xx:xx, 25:xx:xx en 00:xx:xx

In mijn ogen zijn dit outliers. Het gaat om gevallen waarbij mensen hun televisie laten spelen na speciale evenementen zoals oudejaar, voetbalwedstrijden, ...

Ik heb dan ook besloten om deze *ruis* te verwijderen uit de data.

In [114]:
# Get all items that start after midnight
broadcasts_after_midnight = ratings_df[ratings_df["Start"].str.startswith("24:") | ratings_df["Start"].str.startswith("25:") | ratings_df["Start"].str.startswith("00:")]
broadcasts_after_midnight.shape

(44, 10)

In [115]:
# Drop these rows
ratings_df = ratings_df[~ratings_df["Start"].str.startswith("24:") & ~ratings_df["Start"].str.startswith("25:")]
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63208 entries, 0 to 63249
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Programma  63208 non-null  object
 1   Zender     63208 non-null  object
 2   Datum      63208 non-null  datetime64[ns]
 3   Start      63208 non-null  object
 4   Duur       63208 non-null  object
 5   Kijkers    63208 non-null  int64
 6   Jaar       63208 non-null  int32
 7   Maand      63208 non-null  int32
 8   Dag        63208 non-null  int32
 9   Week       63208 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), int32(3), int64(1), object(4)
memory usage: 4.4+ MB

In [116]:
# Convert "Start" and "Duur" to datetime
ratings_df["Start"] = pd.to_datetime(ratings_df["Start"])
ratings_df["Duur"] = pd.to_timedelta(ratings_df["Duur"])

# Calculate end time
ratings_df["Eind"] = ratings_df["Start"] + ratings_df["Duur"]

# Extract start and end hour
ratings_df["Startuur"] = ratings_df["Start"].dt.hour
ratings_df["Einduur"] = ratings_df["Eind"].dt.hour

# # Calculate duration in minutes
ratings_df["Duur"] = ratings_df["Duur"].dt.total_seconds() / 60
ratings_df["Duur"] = ratings_df["Duur"].astype(int)

# Add primetime columns
ratings_df["Primetime"] = (ratings_df["Startuur"] >= 20) & (ratings_df["Einduur"] <= 22)
ratings_df["Einde_In_Primetime"] = (ratings_df["Einduur"] >= 20) & (ratings_df["Einduur"] <= 22)
ratings_df["Start_In_Primetime"] = (ratings_df["Startuur"] >= 20) & (ratings_df["Startuur"] <= 22)

ratings_df.head()

/var/folders/5d/_v0r0r510wncd2w765n36ksw0000gn/T/ipykernel_83230/2307574013.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ratings_df["Start"] = pd.to_datetime(ratings_df["Start"])

,Programma,Zender,Datum,Start,Duur,Kijkers,Jaar,Maand,Dag,Week,Eind,Startuur,Einduur,Primetime,Einde_In_Primetime,Start_In_Primetime
0,HET 7 UUR-JOURNAAL,EEN,2016-10-01,2025-05-25 19:00:05,31,721850,2016,10,5,39,2025-05-25 19:31:43,19,19,False,False,False
1,FC DE KAMPIOENEN,EEN,2016-10-01,2025-05-25 20:41:00,38,709606,2016,10,5,39,2025-05-25 21:19:39,20,21,True,True,True
2,WEG ZIJN WIJ,EEN,2016-10-01,2025-05-25 20:13:36,24,548239,2016,10,5,39,2025-05-25 20:38:20,20,20,True,True,True
3,IEDEREEN BEROEMD,EEN,2016-10-01,2025-05-25 19:38:10,29,523610,2016,10,5,39,2025-05-25 20:07:11,19,20,False,True,False
4,COMEDY TOPPERS,VTM,2016-10-01,2025-05-25 19:52:06,24,496216,2016,10,5,39,2025-05-25 20:16:46,19,20,False,True,False

In [117]:
# Kolommen "Datum", "Start" en "Eind" zijn niet meer nodig, dus we verwijderen ze
ratings_df = ratings_df.drop(columns=["Datum", "Start", "Eind"], axis=1)

ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63208 entries, 0 to 63249
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Programma           63208 non-null  object
 1   Zender              63208 non-null  object
 2   Duur                63208 non-null  int64
 3   Kijkers             63208 non-null  int64
 4   Jaar                63208 non-null  int32
 5   Maand               63208 non-null  int32
 6   Dag                 63208 non-null  int32
 7   Week                63208 non-null  UInt32
 8   Startuur            63208 non-null  int32
 9   Einduur             63208 non-null  int32
 10  Primetime           63208 non-null  bool
 11  Einde_In_Primetime  63208 non-null  bool
 12  Start_In_Primetime  63208 non-null  bool
dtypes: UInt32(1), bool(3), int32(5), int64(2), object(2)
memory usage: 4.1+ MB

Als laatste kijken we verder naar de "Zender" kolom. 

Zenders veranderen af en toe van naam, en dat kunnen we zelf corrigeren.

In [118]:
ratings_df["Zender"].value_counts()

Zender
EEN                       24179
VTM                       19597
VRT 1                      7588
PLAY4                      2507
VIER                       2472
Canvas                     2138
CANVAS                     1819
VRT CANVAS                  959
VTM2                        544
Q2                          532
VITAYA                      221
PLAY5                       189
VIJF                        151
ELEVEN PRO LEAGUE 1 NL      117
VTM3                         52
KETNET                       29
EUROSPORT 1 (NL)             26
OP 12                        14
VTM4                         11
PLAY SPORTS OPEN              9
VTM GOLD                      9
TF1                           7
ZES                           7
LA UNE                        6
RTL-TVI                       6
DAZN PRO LEAGUE 1 (NL)        6
PLAY6                         5
CAZ                           4
EEN,VTM,PLAY4                 1
EEN, VTM, PLAY                1
AB3                           1
VRT 1/VTM/Play4               1
Name: count, dtype: int64

In [123]:
# Zet verschillende waardes voor EEN om
ratings_df.loc[ratings_df["Zender"].isin(["EEN", "VRT 1"]), "Zender"] = "EEN"

# Zet verschillende waardes voor CANVAS om
ratings_df.loc[ratings_df["Zender"].isin(["Canvas", "CANVAS", "VRT CANVAS"]), "Zender"] = "CANVAS"

# Zet verschillende waardes voor KETNET om
ratings_df.loc[ratings_df["Zender"].isin(["KETNET", "OP 12"]), "Zender"] = "KETNET"

# Zet verschillende waardes voor PLAY4 om
ratings_df.loc[ratings_df["Zender"].isin(["VIER", "PLAY4"]), "Zender"] = "PLAY4"

# Zet verschillende waardes voor PLAY5 om
ratings_df.loc[ratings_df["Zender"].isin(["VIJF", "PLAY5"]), "Zender"] = "PLAY5"

# Zet verschillende waardes voor PLAY6 om
ratings_df.loc[ratings_df["Zender"].isin(["ZES", "PLAY6"]), "Zender"] = "PLAY6"

# Zet verschillende waardes voor VTM2 om
ratings_df.loc[ratings_df["Zender"].isin(["Q2", "VTM2"]), "Zender"] = "VTM2"

# Zet verschillende waardes voor VTM3 om
ratings_df.loc[ratings_df["Zender"].isin(["VITAYA", "VTM3"]), "Zender"] = "VTM3"

# Zet verschillende waardes voor VTM4 om
ratings_df.loc[ratings_df["Zender"].isin(["CAZ", "VTM4"]), "Zender"] = "VTM4"

# Wijs programma's over gedeelde zenders toe aan EEN
ratings_df.loc[ratings_df["Zender"].isin(["EEN,VTM,PLAY4", "EEN, VTM, PLAY", "VRT 1/VTM/Play4"]), "Zender"] = "EEN"

# Geef ELEVEN en DAZN dezelfde waarde
ratings_df.loc[ratings_df["Zender"].isin(["ELEVEN PRO LEAGUE 1 NL", "DAZN PRO LEAGUE 1 (NL)"]), "Zender"] = "PRO LEAGUE 1"

ratings_df["Zender"].value_counts()

Zender
EEN                 31770
VTM                 19597
PLAY4                4979
CANVAS               4916
VTM2                 1076
PLAY5                 340
VTM3                  273
PRO LEAGUE 1          123
KETNET                 43
EUROSPORT 1 (NL)       26
VTM4                   15
PLAY6                  12
PLAY SPORTS OPEN        9
VTM GOLD                9
TF1                     7
RTL-TVI                 6
LA UNE                  6
AB3                     1
Name: count, dtype: int64

In [124]:
ratings_df[ratings_df["Zender"] == "EUROSPORT 1 (NL)"]

,Programma,Zender,Duur,Kijkers,Jaar,Maand,Dag,Week,Startuur,Einduur,Primetime,Einde_In_Primetime,Start_In_Primetime
32348,CYCL. TIRRENO-ADRIATICO,EUROSPORT 1 (NL),55,419156,2021,3,5,10,15,16,False,False,False
32374,CYCL. TIRRENO-ADRIATICO,EUROSPORT 1 (NL),149,302009,2021,3,6,10,13,15,False,False,False
33476,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),201,196597,2021,5,5,18,13,17,False,False,False
33497,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),277,124644,2021,5,6,18,12,17,False,False,False
33597,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),299,162573,2021,5,4,19,12,17,False,False,False
33614,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),263,220703,2021,5,5,19,12,16,False,False,False
33632,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),261,280745,2021,5,6,19,12,16,False,False,False
33699,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),353,188426,2021,5,2,20,11,16,False,False,False
33752,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),373,244029,2021,5,5,20,10,16,False,False,False
33774,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),311,179783,2021,5,6,20,12,17,False,False,False
33898,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),312,102118,2021,5,5,21,11,16,False,False,False
47269,CYCL. TIRRENO-ADRIATICO,EUROSPORT 1 (NL),168,132292,2023,3,4,10,13,16,False,False,False
47289,CYCL. TIRRENO-ADRIATICO,EUROSPORT 1 (NL),91,149574,2023,3,5,10,15,16,False,False,False
47569,CYCL. VOLTA A CATALUNYA,EUROSPORT 1 (NL),113,111218,2023,3,5,12,14,16,False,False,False
48289,SNOOKER. WORLD CHAMPIONSHIP,EUROSPORT 1 (NL),187,129238,2023,4,6,17,20,23,False,False,True
48303,SNOOKER. WORLD CHAMPIONSHIP,EUROSPORT 1 (NL),183,288787,2023,5,0,18,20,23,False,False,True
48509,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),274,132924,2023,5,3,19,12,17,False,False,False
48524,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),366,162737,2023,5,4,19,11,17,False,False,False
48545,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),321,116815,2023,5,5,19,11,16,False,False,False
48563,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),248,172481,2023,5,6,19,13,17,False,False,False
48709,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),337,95099,2023,5,6,20,11,17,False,False,False
48806,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),346,137747,2023,5,4,21,11,17,False,False,False
48829,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),147,117021,2023,5,5,21,16,18,False,False,False
55829,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),28,103783,2024,5,5,19,16,17,False,False,False
56407,TENNIS. ROLAND GARROS,EUROSPORT 1 (NL),308,45962,2024,6,6,23,15,20,False,True,False
63247,CYCL. GIRO D'ITALIA,EUROSPORT 1 (NL),288,107122,2025,5,5,20,12,16,False,False,False