In [1]:
# Add the project root to the Python path
import sys
import os
sys.path.append(os.path.join(os.getcwd(), '..'))

from src.config.logging_config import setup_logging
from src.extract.weather_data import fetch_weather_data

In [2]:
logger = setup_logging(log_file="weather_data.log")

df = fetch_weather_data("2025-01-01", "2025-01-03")

2025-09-29 11:32:20,549 - src.extract.weather_data - INFO - Fetching weather data from 2025-01-01 to 2025-01-03
2025-09-29 11:32:20,550 - src.data_sources.weather - INFO - Fetching historical weather data from 2025-01-01 to 2025-01-03
2025-09-29 11:32:20,579 - src.data_sources.weather - INFO - Successfully processed 3 weather records
2025-09-29 11:32:20,579 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 3
2025-09-29 11:32:20,580 - src.extract.weather_data - INFO - Creating DataFrame from 3 records
2025-09-29 11:32:20,582 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 3

In [3]:
df.head()

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,sunrise_time,sunset_time
0,2025-01-01 00:00:00+00:00,63.0,6.644001,8.868999,3.119,1735717487,1735746482,28995.429688,0.000000,10.200000,10.200000,0.00,6.0,35.302494,75.959999,2025-01-01 07:44:47,2025-01-01 15:48:02
1,2025-01-02 00:00:00+00:00,73.0,2.739834,5.719000,0.569,1735803881,1735832945,29065.738281,22633.167969,9.700001,8.799999,0.63,10.0,14.039999,28.440001,2025-01-02 07:44:41,2025-01-02 15:49:05
2,2025-01-03 00:00:00+00:00,51.0,0.641917,2.769000,-1.281,1735890270,1735919411,29141.431641,20559.496094,0.100000,0.100000,0.00,1.0,15.133923,34.200001,2025-01-03 07:44:30,2025-01-03 15:50:11

In [4]:
df = fetch_weather_data("2025-09-30", "2025-10-01")
df.head()

2025-09-29 11:32:20,622 - src.extract.weather_data - INFO - Fetching weather data from 2025-09-30 to 2025-10-01
2025-09-29 11:32:20,630 - src.data_sources.weather - INFO - Fetching forecast weather data from 2025-09-30 to 2025-10-01
2025-09-29 11:32:20,643 - src.data_sources.weather - INFO - Successfully processed 2 weather records
2025-09-29 11:32:20,644 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2
2025-09-29 11:32:20,645 - src.extract.weather_data - INFO - Creating DataFrame from 2 records
2025-09-29 11:32:20,648 - src.extract.weather_data - INFO - Weather data collection complete! Total records: 2

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,sunrise_time,sunset_time
0,2025-09-30 00:00:00+00:00,3.0,15.183167,19.204000,11.554,1759210918,1759252986,42065.398438,26353.244141,0.0,0.0,0.0,0.0,14.04,29.16,2025-09-30 05:41:58,2025-09-30 17:23:06
1,2025-10-01 00:00:00+00:00,3.0,13.369667,17.903999,8.900,1759297414,1759339251,41835.035156,37995.335938,0.0,0.0,0.0,0.0,10.08,23.40,2025-10-01 05:43:34,2025-10-01 17:20:51